### ISSUE TITLE
Lat

### ISSUE THREAD

**Issue by martinhetschel** [AM2H-Development/AM2H-Server#5]
logger::::every mh/event/timer/seconds 2017-04-23T23:59:59+02:00
/home/pi/AM2H-Server/mqttTimer.js:87
                obj.sunTimes = SunCalc.getTimes(new Date(),this.cfg.latitude, this.cfg.longitude);
                                                                   ^

TypeError: Cannot read property 'latitude' of undefined
    at Timeout.poll [as _onTimeout] (/home/pi/AM2H-Server/mqttTimer.js:87:68)
    at ontimeout (timers.js:384:18)
    at tryOnTimeout (timers.js:244:5)
    at Timer.listOnTimeout (timers.js:214:5)

**Comment by martinhetschel** [comment]
fixed this->obj
